name: Publish to Modrinth and CurseForge

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Java
        uses: actions/setup-java@8df1039f650269edb4d16fe02a0a3aefdf92878b # v4.7.0
        with:
          java-version: '21' 
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Read Properties
        id: read_properties
        run: |
          VERSION=$(grep 'mod_version' gradle.properties | cut -d'=' -f2)
          echo "MOD_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish to Modrinth and CurseForge
        uses: Kir-Antipov/mc-publish@4b830a3b2b4d99c4d9241940989f6655a6d962c5 # v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          files: build/libs/safepaths-${{ env.MOD_VERSION }}.jar
